name: Scrape and Upload to Google Sheets

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日9時に自動実行
  workflow_dispatch:     # 手動実行用トリガー

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python your_scraper_script.py
